import { randomBytes, scrypt } from "node:crypto";
import prisma from "./client";

const email = process.env.ADMIN_EMAIL;
const password = process.env.ADMIN_PASSWORD;
const agentEmail = process.env.AGENT_EMAIL;
const agentPassword = process.env.AGENT_PASSWORD;

if (!email || !password) {
  console.error("ADMIN_EMAIL and ADMIN_PASSWORD must be set in .env");
  process.exit(1);
}

if (!agentEmail || !agentPassword) {
  console.error("AGENT_EMAIL and AGENT_PASSWORD must be set in .env");
  process.exit(1);
}

function hashPassword(plain: string): Promise<string> {
  const salt = randomBytes(16).toString("hex");
  return new Promise((resolve, reject) => {
    scrypt(plain.normalize("NFKC"), salt, 64, { N: 16384, r: 16, p: 1, maxmem: 128 * 16384 * 16 * 2 }, (err, key) => {
      if (err) reject(err);
      else resolve(`${salt}:${key.toString("hex")}`);
    });
  });
}

async function createUser(name: string, email: string, password: string, role: "admin" | "agent") {
  const existing = await prisma.user.findUnique({ where: { email } });
  if (existing) {
    console.log(`${name} user already exists, skipping.`);
    return;
  }

  const hashed = await hashPassword(password);
  const userId = crypto.randomUUID();

  await prisma.user.create({
    data: { id: userId, name, email, emailVerified: true, role },
  });

  await prisma.account.create({
    data: { id: crypto.randomUUID(), accountId: userId, providerId: "credential", userId, password: hashed },
  });

  console.log(`${name} user created: ${email}`);
}

const tickets = [
  // Refund requests
  { subject: "Refund for duplicate charge", body: "I was charged twice for my order #8821 placed on April 10th. Please refund the duplicate payment of $49.99.", senderName: "James Whitfield", senderEmail: "james.whitfield@gmail.com", status: "open", category: "refund_request", createdAt: new Date("2026-04-01T08:12:00Z") },
  { subject: "Wrong item delivered — requesting refund", body: "I ordered a blue hoodie size L but received a red t-shirt size M. I'd like a full refund instead of a replacement.", senderName: "Priya Nair", senderEmail: "priya.nair@outlook.com", status: "resolved", category: "refund_request", createdAt: new Date("2026-04-02T10:45:00Z") },
  { subject: "Refund request — cancelled subscription still charged", body: "I cancelled my Pro subscription on March 28th but was still charged $29.99 on April 1st. Requesting a refund.", senderName: "Carlos Méndez", senderEmail: "carlos.mendez@yahoo.com", status: "closed", category: "refund_request", createdAt: new Date("2026-04-03T14:20:00Z") },
  { subject: "Item never arrived — need refund", body: "My order #4492 was marked as delivered on March 30th but I never received it. Package may have been stolen. Please refund.", senderName: "Sophie Turner", senderEmail: "sophie.turner@proton.me", status: "open", category: "refund_request", createdAt: new Date("2026-04-03T16:05:00Z") },
  { subject: "Refund for defective product", body: "The wireless earbuds I received stopped working after two days. The left earbud has no audio output. I'd like a refund.", senderName: "Raj Patel", senderEmail: "raj.patel@gmail.com", status: "open", category: "refund_request", createdAt: new Date("2026-04-04T09:30:00Z") },
  { subject: "Overcharged on annual plan", body: "I signed up for the annual plan at $99 but was charged $120. The discount code ANNUAL20 wasn't applied. Please refund the difference.", senderName: "Mei Lin", senderEmail: "mei.lin@fastmail.com", status: "resolved", category: "refund_request", createdAt: new Date("2026-04-04T11:00:00Z") },
  { subject: "Accidental purchase — refund please", body: "My 8-year-old accidentally purchased a premium add-on for $14.99 while using my device. I'd like a refund as this was unintended.", senderName: "David Okonkwo", senderEmail: "d.okonkwo@gmail.com", status: "closed", category: "refund_request", createdAt: new Date("2026-04-05T07:55:00Z") },
  { subject: "Product not as described — refund", body: "The laptop stand I purchased claims to hold up to 17\" laptops, but it can barely hold my 15\" without wobbling. Very misleading. Requesting refund.", senderName: "Laura Svensson", senderEmail: "l.svensson@outlook.com", status: "open", category: "refund_request", createdAt: new Date("2026-04-05T13:40:00Z") },
  { subject: "Charged after cancellation", body: "I cancelled my account on March 15th and received a confirmation email, yet I was still charged on April 1st. Please issue a refund immediately.", senderName: "Ahmed Hassan", senderEmail: "a.hassan@gmail.com", status: "resolved", category: "refund_request", createdAt: new Date("2026-04-06T08:10:00Z") },
  { subject: "Partial refund for missing items", body: "My order #7734 arrived but two items (USB-C cable and phone stand) were missing from the box. Please refund $23.48 for the missing items.", senderName: "Emma Kowalski", senderEmail: "emma.kowalski@gmail.com", status: "open", category: "refund_request", createdAt: new Date("2026-04-06T15:22:00Z") },

  // Technical questions
  { subject: "API rate limit keeps hitting 429", body: "Our integration keeps hitting 429 Too Many Requests even though we're well under the documented 1000 req/min limit. Is there a per-endpoint limit I'm missing?", senderName: "Tyler Brooks", senderEmail: "tyler.brooks@devco.io", status: "open", category: "technical_question", createdAt: new Date("2026-04-01T09:00:00Z") },
  { subject: "Webhook payload not arriving", body: "I've set up the webhook for order.created events but payloads aren't reaching our endpoint. The endpoint returns 200. Firewall is open. Any debugging tips?", senderName: "Aisha Kamara", senderEmail: "aisha@startupxyz.com", status: "open", category: "technical_question", createdAt: new Date("2026-04-02T14:15:00Z") },
  { subject: "SSO login failing with SAML error", body: "Our Okta SAML integration broke after we updated our subdomain. Users get 'Invalid audience' error. Our entity ID and ACS URL are correct — what else could cause this?", senderName: "Niko Hoffman", senderEmail: "niko.hoffman@enterprise.de", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-02T16:30:00Z") },
  { subject: "Export to CSV missing columns", body: "When I export tickets to CSV, the 'Assigned Agent' and 'Category' columns are missing. This used to work. Is this a regression?", senderName: "Grace Oduya", senderEmail: "grace.oduya@consultancy.co.uk", status: "open", category: "technical_question", createdAt: new Date("2026-04-03T10:00:00Z") },
  { subject: "2FA app not accepting codes", body: "I set up TOTP 2FA yesterday and it was working fine, but today my authenticator app codes are rejected. I've checked the time sync on my phone. Account is locked now.", senderName: "Ivan Petrov", senderEmail: "ivan.petrov@mail.ru", status: "open", category: "technical_question", createdAt: new Date("2026-04-04T08:45:00Z") },
  { subject: "PDF export renders blank pages", body: "Exporting reports as PDF gives a file with correct number of pages but all are blank. Tried Chrome and Firefox. Using macOS 14.4. Started happening this week.", senderName: "Fatima Al-Rashid", senderEmail: "fatima@alrashid.ae", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-04T12:00:00Z") },
  { subject: "Mobile app crashes on iOS 17.4", body: "After updating to iOS 17.4, the app crashes immediately on launch. Clean reinstall didn't help. Crash log attached. Device: iPhone 14 Pro.", senderName: "Lucas Ferreira", senderEmail: "lucas.ferreira@gmail.com", status: "open", category: "technical_question", createdAt: new Date("2026-04-05T09:20:00Z") },
  { subject: "Bulk import fails for files over 5MB", body: "Trying to import a 7MB CSV of 3,000 contacts. Upload completes but then the import job shows 'Failed' with no error message. Smaller files work fine.", senderName: "Hannah Schmidt", senderEmail: "h.schmidt@agentur.de", status: "open", category: "technical_question", createdAt: new Date("2026-04-05T11:15:00Z") },
  { subject: "Search returning irrelevant results", body: "Full-text search stopped returning accurate results yesterday. Searching for 'invoice' returns tickets about shipping. Is the index corrupted?", senderName: "Yusuf Adeyemi", senderEmail: "yusuf@techhub.ng", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-06T09:00:00Z") },
  { subject: "Dark mode not saving preference", body: "Every time I refresh the page, dark mode resets to light. The toggle works but doesn't persist. I've tried clearing cookies and cache.", senderName: "Chloe Martin", senderEmail: "chloe.martin@free.fr", status: "open", category: "technical_question", createdAt: new Date("2026-04-06T13:30:00Z") },
  { subject: "Email notifications delayed by hours", body: "We're receiving email notifications 3-5 hours after events. This is causing missed SLA breaches. Using the default SMTP setup. No changes made on our side.", senderName: "Marcus Webb", senderEmail: "m.webb@logistics.com", status: "open", category: "technical_question", createdAt: new Date("2026-04-07T08:00:00Z") },
  { subject: "API pagination returns duplicate records", body: "When fetching /api/orders with page=2&limit=25, some records from page 1 appear in page 2 results. This breaks our sync logic.", senderName: "Sung-Min Park", senderEmail: "sungmin@koreantech.kr", status: "open", category: "technical_question", createdAt: new Date("2026-04-07T10:30:00Z") },
  { subject: "Custom domain SSL certificate error", body: "After pointing our custom domain to your servers, users get SSL_ERROR_RX_RECORD_TOO_LONG in Firefox. Chrome shows ERR_SSL_PROTOCOL_ERROR. Certificate was provisioned yesterday.", senderName: "Valentina Romano", senderEmail: "v.romano@studio.it", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-07T14:00:00Z") },
  { subject: "Zapier integration not triggering", body: "Our Zapier zap for 'new ticket created' hasn't fired in 2 days even though new tickets are coming in. Tested the trigger manually — nothing. API key is valid.", senderName: "Ben Carter", senderEmail: "ben@automatedhq.com", status: "open", category: "technical_question", createdAt: new Date("2026-04-08T09:15:00Z") },
  { subject: "Charts not loading in Safari", body: "The analytics charts on the dashboard fail to render in Safari 17. I see a blank canvas. Works perfectly in Chrome. Console shows 'ResizeObserver loop limit exceeded'.", senderName: "Brigitte Leblanc", senderEmail: "b.leblanc@agence.fr", status: "open", category: "technical_question", createdAt: new Date("2026-04-08T11:45:00Z") },

  // General questions
  { subject: "How do I add a team member?", body: "I'm trying to invite a colleague to our workspace but can't find the option. We're on the Business plan. Can you walk me through the steps?", senderName: "Olivia Chen", senderEmail: "olivia.chen@startup.com", status: "closed", category: "general_question", createdAt: new Date("2026-04-01T10:00:00Z") },
  { subject: "What's the difference between plans?", body: "I'm comparing the Pro and Business plans. The pricing page mentions 'advanced reporting' for Business but doesn't explain what that includes. Can you clarify?", senderName: "Robert Kim", senderEmail: "robert.kim@consulting.com", status: "resolved", category: "general_question", createdAt: new Date("2026-04-01T12:30:00Z") },
  { subject: "How to change billing email?", body: "Our billing email is set to an employee who left the company. I need to update it to finance@mycompany.com. I can't find this in account settings.", senderName: "Diana Flores", senderEmail: "diana.flores@mycompany.com", status: "resolved", category: "general_question", createdAt: new Date("2026-04-02T09:00:00Z") },
  { subject: "Can I export my data?", body: "We're evaluating whether to continue with your service. Before deciding, I need to know if we can export all our ticket history and customer data in a standard format.", senderName: "Patrick O'Brien", senderEmail: "patrick@obriencorp.ie", status: "closed", category: "general_question", createdAt: new Date("2026-04-02T11:00:00Z") },
  { subject: "Do you have a mobile app?", body: "Is there a native iOS or Android app available? The mobile website works but isn't great for quickly responding to tickets on the go.", senderName: "Amara Diallo", senderEmail: "amara.diallo@ngo.org", status: "closed", category: "general_question", createdAt: new Date("2026-04-03T08:00:00Z") },
  { subject: "Changing account owner", body: "Our company was acquired and I need to transfer account ownership to the new parent company's admin. What's the process for doing this?", senderName: "Stefan Keller", senderEmail: "stefan.keller@newparent.com", status: "open", category: "general_question", createdAt: new Date("2026-04-03T13:00:00Z") },
  { subject: "GDPR data deletion request", body: "A customer has submitted a GDPR right-to-erasure request. Can you advise how to permanently delete all data associated with their email address from your system?", senderName: "Anna Müller", senderEmail: "anna.mueller@dsgvo.de", status: "resolved", category: "general_question", createdAt: new Date("2026-04-04T10:00:00Z") },
  { subject: "How long are tickets retained?", body: "Our compliance team needs to know the data retention policy for closed tickets. How long are they kept before deletion?", senderName: "James Osei", senderEmail: "j.osei@fintech.gh", status: "resolved", category: "general_question", createdAt: new Date("2026-04-04T14:00:00Z") },
  { subject: "Can two agents share one account?", body: "We only have budget for one agent seat but have two part-time support staff. Is sharing credentials against your terms of service?", senderName: "Rosa Delgado", senderEmail: "rosa.delgado@shop.mx", status: "closed", category: "general_question", createdAt: new Date("2026-04-05T08:30:00Z") },
  { subject: "Holiday auto-reply setup", body: "We'll be closed from April 25–28 for a public holiday. How do I set up an automatic reply to let customers know about our response time delay?", senderName: "Kofi Mensah", senderEmail: "kofi@mensahltd.com", status: "resolved", category: "general_question", createdAt: new Date("2026-04-05T10:15:00Z") },
  { subject: "Is there a free trial available?", body: "I'd like to evaluate your service before committing to a paid plan. Do you offer a free trial, and if so, what features are included?", senderName: "Sylvia Park", senderEmail: "sylvia.park@newbiz.io", status: "closed", category: "general_question", createdAt: new Date("2026-04-06T09:30:00Z") },
  { subject: "Uptime SLA for enterprise plan", body: "We're negotiating an enterprise contract. What is the guaranteed uptime SLA and what compensation is offered if it's not met?", senderName: "Michael Andersen", senderEmail: "m.andersen@bigcorp.dk", status: "open", category: "general_question", createdAt: new Date("2026-04-06T11:00:00Z") },
  { subject: "Language support for Spanish", body: "Our customers are primarily Spanish-speaking. Does the customer-facing interface support Spanish, and can agent replies be sent in Spanish?", senderName: "Isabella Morales", senderEmail: "i.morales@latinshop.co", status: "resolved", category: "general_question", createdAt: new Date("2026-04-07T09:00:00Z") },
  { subject: "How to merge duplicate tickets?", body: "A customer submitted the same issue three times. I'd like to merge them into one ticket to keep our history clean. Is that possible?", senderName: "Thomas Nguyen", senderEmail: "thomas.nguyen@support.vn", status: "closed", category: "general_question", createdAt: new Date("2026-04-07T12:00:00Z") },
  { subject: "Do you offer phone support?", body: "For urgent issues I'd prefer to talk to someone rather than waiting for email replies. Is phone or live chat support available on any plan?", senderName: "Fatou Bah", senderEmail: "fatou.bah@commerce.sn", status: "closed", category: "general_question", createdAt: new Date("2026-04-07T15:00:00Z") },
  { subject: "Ticket assignment rules", body: "Is it possible to automatically assign tickets to specific agents based on keywords or categories? We want refund requests to go straight to our billing team.", senderName: "George Papadopoulos", senderEmail: "g.papadopoulos@hellas.gr", status: "open", category: "general_question", createdAt: new Date("2026-04-08T08:30:00Z") },
  { subject: "Account suspended — why?", body: "I logged in this morning to find my account suspended. I haven't violated any terms. No warning email was received. Please investigate urgently.", senderName: "Nadia Fontaine", senderEmail: "nadia.fontaine@boutique.fr", status: "open", category: "general_question", createdAt: new Date("2026-04-08T10:00:00Z") },
  { subject: "How to downgrade my plan?", body: "We're scaling back our team and no longer need the Business plan. How do I downgrade to Pro, and will I receive a prorated refund for the current billing period?", senderName: "Will Torres", senderEmail: "will.torres@agency.com", status: "resolved", category: "general_question", createdAt: new Date("2026-04-08T13:00:00Z") },
  { subject: "What happens to data if I cancel?", body: "If I cancel my subscription, can I still access or download my ticket history? For how long? I need this for our records.", senderName: "Lena Bergström", senderEmail: "lena.bergstrom@nordic.se", status: "resolved", category: "general_question", createdAt: new Date("2026-04-09T09:00:00Z") },
  { subject: "Setting business hours", body: "I want to configure business hours so that our response-time SLA clock only ticks during working hours (Mon–Fri, 9am–6pm CET). Where is this setting?", senderName: "Omar Shaikh", senderEmail: "omar.shaikh@support.pk", status: "open", category: "general_question", createdAt: new Date("2026-04-09T10:30:00Z") },

  // More technical questions
  { subject: "OAuth redirect URI mismatch", body: "Getting 'redirect_uri_mismatch' error when users try to log in via Google OAuth. The URI is registered correctly in our Google Console. Started happening after we migrated to HTTPS.", senderName: "Alex Turner", senderEmail: "alex.turner@saas.io", status: "open", category: "technical_question", createdAt: new Date("2026-04-09T08:00:00Z") },
  { subject: "Rate limiting on password reset", body: "Our automated testing triggers many password reset emails and we're hitting a rate limit. Is there a way to whitelist our test accounts or raise the limit?", senderName: "Preethi Subramaniam", senderEmail: "preethi@qateam.in", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-09T11:00:00Z") },
  { subject: "Timezone not reflected in reports", body: "Reports show timestamps in UTC but I've set my timezone to JST (UTC+9) in my profile. The setting seems to be ignored everywhere except the dashboard header.", senderName: "Haruto Yamamoto", senderEmail: "h.yamamoto@kaisha.jp", status: "open", category: "technical_question", createdAt: new Date("2026-04-09T13:00:00Z") },
  { subject: "Attachment upload failing silently", body: "When agents try to attach files to replies, the upload spinner shows briefly then disappears with no error. Files are under 10MB. Started after the April 5th update.", senderName: "Chidi Ezekwesili", senderEmail: "chidi@techfirm.ng", status: "open", category: "technical_question", createdAt: new Date("2026-04-10T08:30:00Z") },
  { subject: "Custom status not appearing in filters", body: "I created a custom ticket status called 'Pending Customer' but it doesn't appear as an option in the filter dropdown on the tickets list page. Bug?", senderName: "Ingrid Holm", senderEmail: "ingrid.holm@norsk.no", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-10T10:00:00Z") },
  { subject: "Notifications not working in Firefox", body: "Browser push notifications work in Chrome but not Firefox 124. The permission has been granted. Notifications show as 'sent' in the admin panel but never arrive.", senderName: "Marco Ricci", senderEmail: "marco.ricci@webdev.it", status: "open", category: "technical_question", createdAt: new Date("2026-04-10T12:00:00Z") },
  { subject: "SLA timer counting weekends", body: "Our SLA timer is including Saturday and Sunday in the response time calculation even though we've set business hours to Mon–Fri. Is there a separate setting for this?", senderName: "Paula Ostrowski", senderEmail: "paula.o@helpdesk.pl", status: "open", category: "technical_question", createdAt: new Date("2026-04-11T09:00:00Z") },
  { subject: "IP whitelist not blocking correctly", body: "I added our office IP range to the allowlist but users outside that range can still access the admin panel. The feature appears to be enabled. Am I missing a step?", senderName: "Sean Murphy", senderEmail: "sean.murphy@irishtech.ie", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-11T11:30:00Z") },
  { subject: "Canned responses not saving formatting", body: "When I save a canned response with bold text and bullet points, it loses all formatting when inserted into a reply. Plain text only. Is rich text not supported?", senderName: "Asmaa El-Sayed", senderEmail: "asmaa@support.eg", status: "open", category: "technical_question", createdAt: new Date("2026-04-11T14:00:00Z") },
  { subject: "Reports dashboard loading slowly", body: "The analytics dashboard takes 20–30 seconds to load. We have about 15,000 tickets in the system. Is there an indexing issue or a way to speed this up?", senderName: "Derek Walsh", senderEmail: "derek.walsh@agency.ie", status: "open", category: "technical_question", createdAt: new Date("2026-04-12T08:00:00Z") },

  // More refund requests
  { subject: "Refund — service was down during my subscription", body: "Your platform had a major outage from April 3–5 (confirmed on your status page). I paid for a full month of service. I'd like a prorated refund for 3 days.", senderName: "Victor Popescu", senderEmail: "victor.popescu@firma.ro", status: "resolved", category: "refund_request", createdAt: new Date("2026-04-12T09:00:00Z") },
  { subject: "Charged wrong currency", body: "My account is set to GBP but I was charged in USD ($89) instead of £71. The exchange rate used was unfavorable. Please refund and recharge in GBP.", senderName: "Nneka Obi", senderEmail: "nneka.obi@media.co.uk", status: "open", category: "refund_request", createdAt: new Date("2026-04-12T11:00:00Z") },
  { subject: "Refund for unused annual seats", body: "We purchased 10 agent seats but only ever used 4. We're now cancelling. Can we get a refund for the 6 unused seats for the remaining 8 months?", senderName: "Frank Baumann", senderEmail: "frank.baumann@gmbh.de", status: "open", category: "refund_request", createdAt: new Date("2026-04-13T08:30:00Z") },
  { subject: "Promotional price not applied at checkout", body: "I used promo code SPRING25 but was charged full price at checkout. The code showed as valid before I entered payment details. Please refund the $25 difference.", senderName: "Tanya Singh", senderEmail: "tanya.singh@ecommerce.in", status: "resolved", category: "refund_request", createdAt: new Date("2026-04-13T10:00:00Z") },
  { subject: "Refund request — changed my mind", body: "I purchased the annual plan yesterday but decided it's not the right fit for my team right now. Can I get a full refund? It's been less than 24 hours.", senderName: "Jules Renard", senderEmail: "jules.renard@freelance.fr", status: "closed", category: "refund_request", createdAt: new Date("2026-04-13T14:00:00Z") },
  { subject: "Double-billed after plan upgrade", body: "I upgraded from Pro to Business mid-cycle and was charged for both plans for the same period. Order references #PRO-2291 and #BIZ-0043. Please refund the overlap.", senderName: "Chioma Eze", senderEmail: "chioma.eze@startup.ng", status: "open", category: "refund_request", createdAt: new Date("2026-04-14T09:00:00Z") },

  // More general questions
  { subject: "Can I use my own email domain for replies?", body: "Is it possible to configure outgoing ticket replies to come from support@mycompany.com rather than your default noreply address?", senderName: "Anders Lindqvist", senderEmail: "anders@nordic.se", status: "resolved", category: "general_question", createdAt: new Date("2026-04-14T10:30:00Z") },
  { subject: "Slack integration setup", body: "I want to get Slack notifications when high-priority tickets come in. Is there a Slack integration and where do I configure it?", senderName: "Keisha Brown", senderEmail: "keisha.brown@consultancy.com", status: "resolved", category: "general_question", createdAt: new Date("2026-04-14T13:00:00Z") },
  { subject: "How to bulk close tickets?", body: "We have hundreds of tickets from an old promotion that are now irrelevant. Is there a way to bulk-select and close them instead of closing one by one?", senderName: "Paulo Figueiredo", senderEmail: "paulo.f@ecommerce.br", status: "open", category: "general_question", createdAt: new Date("2026-04-15T08:30:00Z") },
  { subject: "Custom fields for tickets", body: "We need to capture additional information like order number and product line when tickets are created. Does your system support custom fields?", senderName: "Marta Kowalczyk", senderEmail: "marta.k@enterprise.pl", status: "open", category: "general_question", createdAt: new Date("2026-04-15T10:00:00Z") },
  { subject: "How to create canned responses?", body: "I'd like to create templated responses for common questions to speed up my agents' workflow. Where do I set up canned responses?", senderName: "Jamal Osei-Bonsu", senderEmail: "jamal@supportpro.gh", status: "closed", category: "general_question", createdAt: new Date("2026-04-15T12:00:00Z") },
  { subject: "API key rotation policy", body: "Our security policy requires rotating API keys every 90 days. What's the procedure for generating a new key without disrupting our integration?", senderName: "Linh Nguyen", senderEmail: "linh.nguyen@techvn.vn", status: "resolved", category: "general_question", createdAt: new Date("2026-04-16T09:00:00Z") },
  { subject: "Ticket tagging best practices", body: "We want to start tagging tickets for better reporting. Are there any best practices or limits on the number of tags per ticket?", senderName: "Carlos Ruiz", senderEmail: "c.ruiz@support.es", status: "closed", category: "general_question", createdAt: new Date("2026-04-16T11:30:00Z") },
  { subject: "Training materials for new agents", body: "We're onboarding three new support agents next week. Do you have video tutorials or documentation specifically for agents getting started?", senderName: "Beth Cunningham", senderEmail: "beth@helpdeskhq.com", status: "resolved", category: "general_question", createdAt: new Date("2026-04-16T14:00:00Z") },
  { subject: "Multiple inboxes for different products", body: "We have two products and want separate inboxes so tickets don't get mixed up. Can we set up multiple inboxes under one account?", senderName: "Rohan Mehta", senderEmail: "rohan.mehta@productstudio.in", status: "open", category: "general_question", createdAt: new Date("2026-04-17T08:00:00Z") },
  { subject: "Customer satisfaction survey setup", body: "I'd like to automatically send a satisfaction rating request after a ticket is closed. Is there a built-in CSAT feature or do I need a third-party integration?", senderName: "Claire Dupont", senderEmail: "claire.dupont@support.fr", status: "open", category: "general_question", createdAt: new Date("2026-04-17T10:30:00Z") },

  // More technical
  { subject: "Emails going to spam", body: "Replies sent through your platform are landing in customers' spam folders. SPF and DKIM records are set up correctly. Could there be an issue with your sending IPs?", senderName: "Tom Blackwood", senderEmail: "tom.blackwood@agency.com", status: "open", category: "technical_question", createdAt: new Date("2026-04-17T13:00:00Z") },
  { subject: "API response time degraded", body: "Over the past week, API response times have increased from ~80ms to over 600ms. Our load is the same as always. Is something wrong on your infrastructure?", senderName: "Fiona Grant", senderEmail: "fiona.grant@fintech.co.uk", status: "open", category: "technical_question", createdAt: new Date("2026-04-18T09:00:00Z") },
  { subject: "Session expires too quickly", body: "Agents are getting logged out after about 15 minutes of inactivity, which is very disruptive. We need at least 4 hours. Is the session timeout configurable?", senderName: "Dmitri Volkov", senderEmail: "d.volkov@tech.ru", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-18T11:00:00Z") },
  { subject: "Webhook signature verification failing", body: "We're following your docs to verify webhook signatures using HMAC-SHA256 but verification fails for about 10% of payloads. Possibly a character encoding issue?", senderName: "Sun Wei", senderEmail: "sun.wei@techcompany.cn", status: "open", category: "technical_question", createdAt: new Date("2026-04-18T14:00:00Z") },
  { subject: "Table sorting broken after update", body: "Since the April 15th update, clicking column headers to sort the ticket list does nothing. The URL changes but the order stays the same. Affects all browsers.", senderName: "Elisa Bianchi", senderEmail: "elisa.bianchi@softwarehouse.it", status: "open", category: "technical_question", createdAt: new Date("2026-04-19T08:30:00Z") },
  { subject: "Incorrect unread count badge", body: "The unread tickets badge on the nav shows 47, but when I filter for unread tickets I only see 3. The count doesn't reset even after viewing all tickets.", senderName: "Samuel Okafor", senderEmail: "s.okafor@agency.com.ng", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-19T10:00:00Z") },
  { subject: "Can't delete old account", body: "I have an old account with a former company email. I can no longer access that email to verify deletion. How can I delete it? It's preventing me from using my personal email to sign up.", senderName: "Zara Hussain", senderEmail: "zara.hussain.personal@gmail.com", status: "open", category: "technical_question", createdAt: new Date("2026-04-19T12:30:00Z") },
  { subject: "Batch API endpoint timeout", body: "POST /api/v2/batch times out when sending more than ~50 operations. Payload is under the size limit. Is there an operation count limit not documented?", senderName: "Riku Mäkinen", senderEmail: "riku.makinen@dev.fi", status: "open", category: "technical_question", createdAt: new Date("2026-04-20T08:00:00Z") },

  // More refund requests
  { subject: "Refund — feature I paid for isn't working", body: "I upgraded to Business specifically for the 'Custom Reporting' feature listed on your pricing page. It has been broken since I signed up 3 weeks ago. Requesting refund.", senderName: "Abena Asante", senderEmail: "abena.asante@business.gh", status: "open", category: "refund_request", createdAt: new Date("2026-04-20T09:30:00Z") },
  { subject: "Wrong plan renewed automatically", body: "My team plan expired and auto-renewed at the old price of $199 instead of the current promotional price of $149. I'd like a $50 refund.", senderName: "Boris Novak", senderEmail: "boris.novak@startup.cz", status: "resolved", category: "refund_request", createdAt: new Date("2026-04-20T11:00:00Z") },
  { subject: "Refund for add-on I didn't use", body: "I purchased the 'AI Summaries' add-on three months ago but it never worked with our setup. I've been paying $15/month for nothing. Please refund the $45 total.", senderName: "Helen Crawford", senderEmail: "helen.crawford@smb.co.uk", status: "open", category: "refund_request", createdAt: new Date("2026-04-21T08:30:00Z") },

  // More general questions
  { subject: "How are tickets prioritised by default?", body: "What is the default sort order for tickets in the queue? Is it first-in-first-out or is there a priority algorithm? I want to make sure urgent tickets aren't buried.", senderName: "Kwame Asiedu", senderEmail: "kwame.asiedu@ops.gh", status: "resolved", category: "general_question", createdAt: new Date("2026-04-21T10:00:00Z") },
  { subject: "Privacy policy for EU customers", body: "We have customers in Germany and France who are asking about GDPR compliance. Where can I find your DPA (Data Processing Agreement) to share with them?", senderName: "Hilde Johannessen", senderEmail: "hilde@compliance.no", status: "closed", category: "general_question", createdAt: new Date("2026-04-21T13:00:00Z") },
  { subject: "Can I restrict agent access by category?", body: "I want billing agents to only see refund_request tickets and tech agents to only see technical_question tickets. Is role-based access control available?", senderName: "Teresa Yamada", senderEmail: "teresa.yamada@enterprise.jp", status: "open", category: "general_question", createdAt: new Date("2026-04-22T08:00:00Z") },
  { subject: "Audit log for agent actions", body: "A compliance requirement means we need a full audit trail of who viewed, edited or replied to each ticket. Is there an audit log feature?", senderName: "Eric Vandenberghe", senderEmail: "eric.v@legal.be", status: "open", category: "general_question", createdAt: new Date("2026-04-22T10:30:00Z") },
  { subject: "Pausing subscription for summer", body: "Our business is seasonal and we'll have very little support volume from June through August. Can we pause our subscription instead of cancelling?", senderName: "Ioana Constantin", senderEmail: "ioana.constantin@seasonal.ro", status: "open", category: "general_question", createdAt: new Date("2026-04-22T13:00:00Z") },
  { subject: "Integrating with Salesforce", body: "We use Salesforce as our CRM and want ticket data to sync automatically. Is there a native Salesforce integration or would we need to build one with the API?", senderName: "Mark Sutherland", senderEmail: "mark.s@enterprise.com", status: "resolved", category: "general_question", createdAt: new Date("2026-04-23T09:00:00Z") },
  { subject: "Maximum ticket attachment size", body: "Our customers sometimes need to send large log files or screen recordings as attachments. What is the maximum file size allowed per attachment and per ticket?", senderName: "Yemi Adewale", senderEmail: "yemi.adewale@techco.ng", status: "resolved", category: "general_question", createdAt: new Date("2026-04-23T11:00:00Z") },
  { subject: "Response time benchmarks", body: "What's considered a good first-response time for a SaaS support team our size (5 agents, ~200 tickets/day)? Looking for industry benchmarks to set targets.", senderName: "Cecile Moreau", senderEmail: "cecile.moreau@csm.fr", status: "closed", category: "general_question", createdAt: new Date("2026-04-23T14:00:00Z") },
  { subject: "White-labelling options", body: "We resell your platform to our clients under our own brand. What white-labelling options are available — can we remove all mentions of your company name?", senderName: "Nathan Burke", senderEmail: "nathan@reseller.au", status: "open", category: "general_question", createdAt: new Date("2026-04-24T08:00:00Z") },
  { subject: "How to re-open a closed ticket?", body: "A customer replied to a ticket we marked as closed. The reply created a new ticket instead of re-opening the original. How do we configure it to re-open the original?", senderName: "Min-Ji Lee", senderEmail: "minji.lee@helpdesk.kr", status: "open", category: "general_question", createdAt: new Date("2026-04-24T10:30:00Z") },
  { subject: "Agent performance metrics", body: "I'd like to track individual agent metrics like average reply time, tickets resolved per day, and CSAT score. Are these available in the reporting section?", senderName: "Rashida Osei", senderEmail: "rashida.osei@manager.gh", status: "resolved", category: "general_question", createdAt: new Date("2026-04-24T13:00:00Z") },
  { subject: "Setting up escalation rules", body: "We want tickets that haven't been replied to within 4 hours to automatically escalate to the team lead. How do we configure escalation rules?", senderName: "Josef Novotný", senderEmail: "josef.novotny@support.cz", status: "open", category: "general_question", createdAt: new Date("2026-04-25T08:30:00Z") },
  { subject: "Transferring tickets between inboxes", body: "We created a second inbox for our new product line. How do we move existing tickets from the old inbox to the new one without losing history?", senderName: "Tunde Adeyemi", senderEmail: "tunde.a@product.ng", status: "open", category: "general_question", createdAt: new Date("2026-04-25T10:00:00Z") },
  { subject: "More refund — hardware defective on arrival", body: "The keyboard I received has two keys that don't register (Q and W). This is a manufacturing defect. I'd like a replacement or full refund of $89.99.", senderName: "Lara Santos", senderEmail: "lara.santos@home.br", status: "open", category: "refund_request", createdAt: new Date("2026-04-25T12:00:00Z") },
  { subject: "API key leaked — how to revoke?", body: "I accidentally committed our API key to a public GitHub repo. I've already deleted the commit but need to revoke the key immediately. How do I do this?", senderName: "Hugo Pelletier", senderEmail: "hugo.pelletier@dev.ca", status: "resolved", category: "technical_question", createdAt: new Date("2026-04-25T14:30:00Z") },
  { subject: "Widget not loading on certain pages", body: "The support chat widget loads fine on our homepage but fails to load on our checkout page. Console shows 'Content Security Policy' error. Our CSP is standard.", senderName: "Nour Al-Amin", senderEmail: "nour@ecommerce.sa", status: "open", category: "technical_question", createdAt: new Date("2026-04-26T08:00:00Z") },
  { subject: "Refund — billing resumed after pause request", body: "I submitted a pause request via your support chat on April 10th (ticket #3392). Billing resumed anyway on April 20th. Please refund the $49.99 charged in error.", senderName: "Kirsten Bauer", senderEmail: "kirsten.bauer@freelance.de", status: "open", category: "refund_request", createdAt: new Date("2026-04-26T09:30:00Z") },
  { subject: "Real-time notifications not working", body: "In-app notifications stopped updating in real time. I have to manually refresh to see new tickets. This worked fine before the April 20th maintenance window.", senderName: "Emeka Nwachukwu", senderEmail: "emeka@techstartup.ng", status: "open", category: "technical_question", createdAt: new Date("2026-04-26T11:00:00Z") },
] as const;

async function seedTickets() {
  const count = await prisma.ticket.count();
  if (count >= 100) {
    console.log(`Tickets already seeded (${count}), skipping.`);
    return;
  }

  await prisma.ticket.createMany({ data: tickets.map((t) => ({ ...t })) });
  console.log(`Created ${tickets.length} seed tickets.`);
}

async function seed() {
  await createUser("Admin", email!, password!, "admin");
  await createUser("Agent", agentEmail!, agentPassword!, "agent");
  await seedTickets();
}

seed()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
